[package]
name = "version-info"
version = "1.0.0"
authors = ["yanbowen <yanbowen199407@gmail.com>"]
edition = "2021"

[dependencies]
log = "0.4.7"
serde_json = "1.0"

[build-dependencies]
chrono = "0.4.7"
